name: PostApp # The name of the App
options: # Some general settings for the project
  createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
  bundleIdPrefix: "com.carlosparada"
packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 5.8.0
targets: # The List of our targets
  PostApp:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      #Sources
      - path: PostApp
    postCompileScripts:
      - path: Scripts/swiftlint.sh
        name: Run swiftlint
    dependencies:
      - target: Domain
      - target: Injector
      - package: Kingfisher
  PostAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: PostAppTests
    dependencies:
      - target: PostApp
    settings:
      base:
        INFOPLIST_FILE: PostAppTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.carlosparada
  Data:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Data
    postCompileScripts:
      - path: Scripts/swiftlint.sh
        name: Run swiftlint
    dependencies:
      - target: Domain
    settings:
      base:
        INFOPLIST_FILE: Data/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.carlosparada
  DataTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: DataTests
    dependencies:
      - target: Data
    settings:
      base:
        INFOPLIST_FILE: DataTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.carlosparada
  Domain:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Domain
    postCompileScripts:
      - path: Scripts/swiftlint.sh
        name: Run swiftlint
    settings:
      base:
        INFOPLIST_FILE: Domain/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.carlosparada
  DomainTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: DomainTests
    dependencies:
      - target: Domain
    settings:
      base:
        INFOPLIST_FILE: DomainTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.carlosparada
  Injector:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Injector
    postCompileScripts:
      - path: Scripts/swiftlint.sh
        name: Run swiftlint
    dependencies:
      - target: Domain
    settings:
      base:
        INFOPLIST_FILE: Injector/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.carlosparada
